version: "3.8"

volumes:
  database_volume:

services:
  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: DEVELOPMENT_PASSWORD
      POSTGRES_DB: DEVELOPMENT_DB
    restart: always
    volumes:
      - ./backend/database_volume:/var/lib/postgresql/data
    networks:
      - dev_network

  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
      - 3001:3001
      - 3002:3002
    restart: always
    depends_on:
      - database
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/transcendence
    networks:
      - dev_network

  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - database
      - backend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/transcendence
    networks:
      - dev_network

networks:
  dev_network:
