# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=abc
ENV POSTGRES_PASSWORD=DEVELOPMENT_PASSWORD
ENV POSTGRES_DB=DEVELOPMENT_DB

# Expose the default PostgreSQL port
EXPOSE 5432
